import { createRouter, createWebHistory } from 'vue-router'
import MainView from '@/views/MainView.vue'
import RoutesView from '@/views/RoutesView.vue'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: '/',
      name: 'home',
      component: MainView,
      children: [
        {
          path: 'login',
          name: 'login',
        },
        {
          path: 'settings',
          name: 'settings',
        },
        {
          path: 'routes/:start/:arrival',
          name: 'routes',
          component: RoutesView
        },
        {
          // id will be generated by backend
          // based on mean of transport
          path: 'routes/:start/:arrival/:id',
          name: 'route-details',
        }
      ]
    },    
  ],
})

export default router
