import { createRouter, createWebHistory } from 'vue-router'
import MainView from '@/views/MainView.vue'
import RoutesView from '@/views/RoutesView.vue'
import AuthView from '@/views/AuthView.vue'
import SignInView from '@/views/SignInView.vue'
import SignUpView from '@/views/SignUpView.vue'
import SettingsView from '@/views/SettingsView.vue'
import { getUser } from '@/lib/api'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: '/',
      name: 'home',
      component: MainView,
      children: [
        {
          path: 'auth',
          name: 'auth',
          component: AuthView,
        },
        {
          path: 'auth/signin',
          name: 'signin',
          component: SignInView,
        },
        {
          path: 'auth/signup',
          name: 'signup',
          component: SignUpView,
        },
        {
          path: 'settings',
          name: 'settings',
          component: SettingsView,
          meta: { requiresAuth: true },
        },
        {
          path: 'routes/:start/:arrival',
          name: 'routes',
          component: RoutesView
        },
        {
          // id will be generated by backend
          // based on mean of transport
          path: 'routes/:start/:arrival/:id',
          name: 'route-details',
        }
      ]
    },    
  ],
})

router.beforeEach(async (to, from, next) => {
  const requiresAuth = to.matched.some(record => record.meta.requiresAuth)
  const isAuthenticated = await getUser()
  
  if (requiresAuth && isAuthenticated.result==false) {
    try {
      next({ path: '/auth' })
    } catch (error) {
      console.log(error)
    }
  } else {
    next()
  }
})
export default router