import { createRouter, createWebHistory } from 'vue-router'
import MainView from '@/views/MainView.vue'
import AuthView from '@/views/AuthView.vue'
import SignInView from '@/views/SignInView.vue'
import SignUpView from '@/views/SignUpView.vue'
import LogInView from '@/views/LogInView.vue'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: '/',
      name: 'home',
      component: MainView,
      children: [
        {
          path: 'auth',
          name: 'auth',
          component: AuthView,
        },
        {
          path: 'auth/signin',
          name: 'signin',
          component: SignInView,
        },
        {
          path: 'auth/signup',
          name: 'signup',
          component: SignUpView,
        },
        {
          path: 'auth/login',
          name: 'login',
          component: LogInView,
        },
        {
          path: 'settings',
          name: 'settings',
        },
        {
          path: 'routes/:start/:arrival',
          name: 'routes',
        },
        {
          // id will be generated by backend
          // based on mean of transport
          path: 'routes/:start/:arrival/:id',
          name: 'route-details',
        }
      ]
    },    
  ],
})

export default router
