openapi: 3.0.0
info:
  title: "trentogo"
  description: >
    "webapp to be able to see all of the means of transportation
    in a single application, without having to switch between all different apps."
  version: 0.1.1

#servers:
#  - url: http://api.example.com/v1
#  description: Optional server description, e.g. Main (production) server

paths:
  /auth:
    post:
      summary: "Authentication of a user through credentials."
      description: > 
        "Enables users to authenticate themselves to the web service,
        using email and password."
      requestBody:
        description: "Credentials as email and password."
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "Authentication succesfull. Returns auth token (JWT)."
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "403":
          description: "Authentication failed, because of wrong/invalid credentials."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Email o password non corretta/e."

  /logout:
    get:
      summary: "Logs out the user."
      description: "Logs out the user, expiring the auth token."
      responses:
        "200":
          description: "Logged out succesfully."
        "403":
          description: "User is not logged in."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Non hai fatto l'accesso."
  
  /signup:
    post:
      summary: "Creation of a new user account."
      description: >
        "Registers a new user in the database
        with the info provided in the request."
      requestBody:
        description: >
          "Credentials as email and password and
          personal user's info."
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - fullName
              properties:
                email:
                  type: string
                password:
                  type: string
                fullName:
                  type: string
      responses:
        "200":
          description: >
            "Account created successfully.
            Returns the id."
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                    format: email
        "409":
          description: "Email already registered in the app."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Email già utilizzata."

  /user:
    get:
      summary: "Get current user info and preferences."
      description: "Server returns the authenticated user's information and preferences."
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "Successfully retrieved user info."
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: "user@example.com"
                  fullName:
                    type: string
                    example: "John Doe"
                  preferences:
                    type: object
                    properties:
                      theme:
                        type: string
                        enum: [light, dark, auto]
                        example: "dark"
                      ratingWarning:
                        type: boolean
                      favourites:
                        type: array
                        items:
                          type: object
                          properties:
                            title:
                              type: string
                              example: "Casa"
                            icon:
                              type: string
                              example: "home"
                            color:
                              type: string
                            lat:
                              type: number
                            lng:
                              type: number
        "401":
          description: "Unauthorized - User is not authenticated."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Non hai fatto l'accesso."

  /user/preferences:
    put:
      summary: "Update user preferences."
      description: "Allows the authenticated user to update their preferences."
      security:
        - bearerAuth: []
      requestBody:
        description: "User preferences to be updated."
        content:
          application/json:
            schema:
              type: object
              properties:
                theme:
                  type: string
                  enum: [light, dark, auto]
                ratingWarning:
                  type: boolean
                favourites:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                      icon:
                        type: string
                        enum: [home, work, star]
                      color:
                        type: string
                      lat:
                        type: number
                      lng:
                        type: number
      responses:
        "200":
          description: "Successfully updated user preferences."
          content:
            application/json:
              schema:
                type: object
                properties:
                  theme:
                    type: string
                    enum: [light, dark, auto]
                  ratingWarning:
                    type: boolean
                  favourites:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        icon:
                          type: string
                          enum: [home, work, star]
                        color:
                          type: string
                        lat:
                          type: number
                        lng:
                          type: number
        "401":
          description: "Unauthorized - User is not authenticated."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Non hai fatto l'accesso."

  /user/credit-card-info:
    get:
      summary: "Get user credit card information."
      description: "Returns the authenticated user's credit card information."
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "Successfully retrieved credit card information."
          content:
            application/json:
              schema:
                type: object
                properties:
                  ownerName:
                    type: string
                  ownerSurname:
                    type: string
                  number:
                    type: string
                  cvc:
                    type: string
                  expireAt:
                    type: string
                    format: date
        "401":
          description: "Unauthorized - User is not authenticated."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Non hai fatto l'accesso."

    patch:
      summary: "Update user credit card information."
      description: "Allows the authenticated user to update their credit card information."
      security:
        - bearerAuth: []
      requestBody:
        description: "Credit card information to be updated."
        content:
          application/json:
            schema:
              type: object
              properties:
                ownerName:
                  type: string
                ownerSurname:
                  type: string
                number:
                  type: string
                cvc:
                  type: string
                expireAt:
                  type: string
                  format: date
      responses:
        "200":
          description: "Successfully updated credit card information."
          content:
            application/json:
              schema:
                type: object
                properties:
                  ownerName:
                    type: string
                  ownerSurname:
                    type: string
                  number:
                    type: string
                  cvc:
                    type: string
                  expireAt:
                    type: string
                    format: date
        "401":
          description: "Unauthorized - User is not authenticated."
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Non hai fatto l'accesso."

  /user/favourites:
    post:
      summary: "Add a favourite place."
      description: "Allows the authenticated user to add a favourite place."
      security:
        - bearerAuth: []
      requestBody:
        description: "Favourite place to be added."
        content:
          application/json:
            schema:
              type: object
              properties:
                title:

  /transport/near-bike-stall:
    get:
      summary: "Get the closest bike stall."
      description: "Finds the nearest bike stall to the supplied location."
      responses:
        "200":
          description: >
            "Found bike stall. Returns its coordinates."
          content:
            application/json:
              schema:
                type: object
                properties:
                  lat:
                    type: number
                  lng:
                    type: number
    parameters:
      - name: lat
        in: query
        description: "Latitude of the point"
        required: true
        schema:
          type: number
      - name: long
        in: query
        description: "Longitude of the point"
        required: true
        schema:
          type: number

  /transport/near-scooter:
    get:
      summary: "Get the closest scooter."
      description: "Finds the nearest scooter to the supplied location."
      responses:
        "200":
          description: >
            "Found scooter. Returns its coordinates."
          content:
            application/json:
              schema:
                type: object
                properties:
                  lat:
                    type: number
                  lng:
                    type: number
    parameters:
      - name: lat
        in: query
        description: "Latitude of the point"
        required: true
        schema:
          type: number
      - name: lng
        in: query
        description: "Longitude of the point"
        required: true
        schema:
          type: number